# Generated by Django 5.2.5 on 2025-09-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_status', models.CharField(max_length=10)),
                ('student_ID', models.CharField(max_length=5)),
                ('program_title', models.CharField(max_length=100)),
                ('balance', models.IntegerField()),
                ('program_head', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('honorofics', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('address', models.CharField()),
                ('employee_ID', models.CharField(max_length=5)),
                ('program_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_title', models.CharField(max_length=100)),
                ('program_head', models.CharField(max_length=100)),
                ('degree_duration', models.IntegerField()),
                ('number_of_students', models.IntegerField()),
                ('specialization', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('year_level', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.CharField()),
                ('student_ID', models.CharField(max_length=5)),
                ('program_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('units', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('employee_ID', models.CharField(max_length=5)),
                ('subject_ID', models.CharField(max_length=10)),
            ],
        ),
    ]
