# Generated by Django 5.2.8 on 2025-11-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0002_enrollment_professor_program_student_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='balance',
            field=models.FloatField(),
        ),
    ]
